### ISSUE TITLE
Create_exponential_function()

### ISSUE THREAD

**Issue by RyanLuong1** [RyanLuong1/Cowmos#2]
# Problem
The create_exponential_function() asks the user to input a value n (x^n). After getting the input, it should return a string. For example, if the user gives 5 for n then the string will be "x**5"

# Pseudocode
```
def create_exponential_function():
     n = get the input from user
     return it as x**n
```

**Comment by maikhol** [comment]
Hi could I work on this issue?

**Comment by RyanLuong1** [comment]
go right ahead
